/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshopmanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heinnaingsoe
 */
public class Inventory extends javax.swing.JFrame {

    private String role;
    /**
     * Creates new form Register
     */
    public Inventory() {
        initComponents();
        // Center the window on the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setTitle("Inventory");
    }
    
    public Inventory(String role) {
        this.role = role;
        initComponents();
        // Center the window on the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setTitle("Inventory");
        if (role.equals("Cashier")) { // Check if the user's role is "Cashier"
            // Make the Save, Update, Sale Record and Delete buttons invisible for "Cashier"
            btnSave.setVisible(false);
            btnUpdate.setVisible(false);
            btnDelete.setVisible(false);
            btnSrecord.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        imglogo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        btnInv = new javax.swing.JToggleButton();
        btnSale = new javax.swing.JToggleButton();
        btnSrecord = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        txtcate = new javax.swing.JLabel();
        rbtndog = new javax.swing.JRadioButton();
        rbtncat = new javax.swing.JRadioButton();
        rbtnrabbit = new javax.swing.JRadioButton();
        rbtnbird = new javax.swing.JRadioButton();
        txtQty = new javax.swing.JLabel();
        txtfeId = new javax.swing.JTextField();
        txtfeQty = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnShowtable = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JLabel();
        txtBreed = new javax.swing.JLabel();
        txtfeBreed = new javax.swing.JTextField();
        txtPrice = new javax.swing.JLabel();
        txtfePrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopmanagementsystem/Img/animallogo.jpeg"))); // NOI18N
        jPanel2.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 130));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, 30));

        btnInv.setBackground(new java.awt.Color(153, 255, 255));
        btnInv.setText("Inventory");
        jPanel2.add(btnInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 50));

        btnSale.setText("Sale");
        btnSale.setMaximumSize(new java.awt.Dimension(78, 23));
        btnSale.setMinimumSize(new java.awt.Dimension(78, 23));
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        jPanel2.add(btnSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 50));

        btnSrecord.setText("Sale Record");
        btnSrecord.setMaximumSize(new java.awt.Dimension(78, 23));
        btnSrecord.setMinimumSize(new java.awt.Dimension(78, 23));
        btnSrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrecordActionPerformed(evt);
            }
        });
        jPanel2.add(btnSrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 570));

        jPanel1.setBackground(new java.awt.Color(131, 205, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registration"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcate.setText("Category");
        jPanel1.add(txtcate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup1.add(rbtndog);
        rbtndog.setText("Dog");
        rbtndog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndogActionPerformed(evt);
            }
        });
        jPanel1.add(rbtndog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, -1));

        buttonGroup1.add(rbtncat);
        rbtncat.setText("Cat");
        jPanel1.add(rbtncat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, -1));

        buttonGroup1.add(rbtnrabbit);
        rbtnrabbit.setText("Rabbit");
        jPanel1.add(rbtnrabbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 70, -1));

        buttonGroup1.add(rbtnbird);
        rbtnbird.setText("Bird");
        rbtnbird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnbirdActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnbird, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 70, -1));

        txtQty.setText("Quantity");
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txtfeId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtfeIdMouseReleased(evt);
            }
        });
        txtfeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeIdActionPerformed(evt);
            }
        });
        txtfeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfeIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtfeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, 30));
        jPanel1.add(txtfeQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 220, 30));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 110, 30));

        btnShowtable.setText("Show Table");
        btnShowtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowtableActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 110, 30));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 30));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 110, 30));

        txtSearch.setText("Search by Id");
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        txtBreed.setText("Breed");
        jPanel1.add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(txtfeBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 30));

        txtPrice.setText("Price");
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtfePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtfePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 660, 220));

        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet_Id", "Breed", "Quantity", "Price"
            }
        ));
        tableInventory.setName(""); // NOI18N
        jScrollPane1.setViewportView(tableInventory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 660, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        // TODO add your handling code here:
        new Sale(role).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSaleActionPerformed

    private void btnSrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrecordActionPerformed
        // TODO add your handling code here:
        new SaleRecord(role).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSrecordActionPerformed

    private void rbtnbirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnbirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnbirdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String breed, quantity, price, id;
        breed = txtfeBreed.getText();
        quantity = txtfeQty.getText();
        price = txtfePrice.getText();
        id = txtfeId.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            
            String table = "";
            if (rbtndog.isSelected()) {
            table = "Dog";
            } else if (rbtncat.isSelected()) {
            table = "Cat";
            } else if (rbtnrabbit.isSelected()) {
            table = "Rabbit";
            } else if (rbtnbird.isSelected()) {
            table = "Bird";
            }
            
            String sql = "UPDATE " + table + " SET Breed=?, Quantity=?, Price=? WHERE " + table + "_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, breed);
            pst.setString(2, quantity);
            pst.setString(3, price);
            pst.setString(4, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inventory Updated Successfully!");
            txtfeBreed.setText("");
            txtfeQty.setText("");
            txtfePrice.setText("");
            txtfeId.setText("");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShowtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowtableActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            Statement st = con.createStatement();
            
            String table = "";
            if (rbtndog.isSelected()) {
            table = "Dog";
            } else if (rbtncat.isSelected()) {
            table = "Cat";
            } else if (rbtnrabbit.isSelected()) {
            table = "Rabbit";
            } else if (rbtnbird.isSelected()) {
            table = "Bird";
            }
            
            String sql = "SELECT * FROM " + table;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel dt = (DefaultTableModel)tableInventory.getModel();
            dt.setRowCount(0);
            while(rs.next()){
                Object o[] = {rs.getString(table+"_id"),rs.getString("Breed"),rs.getString("Quantity"),rs.getString("Price")};
                dt.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnShowtableActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            
            String table = "";
            if (rbtndog.isSelected()) {
            table = "Dog";
            } else if (rbtncat.isSelected()) {
            table = "Cat";
            } else if (rbtnrabbit.isSelected()) {
            table = "Rabbit";
            } else if (rbtnbird.isSelected()) {
            table = "Bird";
            }
            
            String breed = txtfeBreed.getText();
            int quantity = Integer.parseInt(txtfeQty.getText());
            int price = Integer.parseInt(txtfePrice.getText());
            
            String sql = "INSERT INTO " + table + " (Breed, Quantity, Price) VALUES (?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, breed);
            pst.setInt(2, quantity);
            pst.setInt(3, price);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Pet added successfully!");
            txtfeBreed.setText("");
            txtfeQty.setText("");
            txtfeId.setText("");
            txtfePrice.setText("");
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtfeId.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            
            String table = "";
            if (rbtndog.isSelected()) {
            table = "Dog";
            } else if (rbtncat.isSelected()) {
            table = "Cat";
            } else if (rbtnrabbit.isSelected()) {
            table = "Rabbit";
            } else if (rbtnbird.isSelected()) {
            table = "Bird";
            }
            
            String sql = "DELETE FROM " + table + " WHERE " + table + "_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inventory Deleted Successfully!");
            txtfeBreed.setText("");
            txtfeQty.setText("");
            txtfePrice.setText("");
            txtfeId.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtfePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfePriceActionPerformed

    private void txtfeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeIdActionPerformed

    private void txtfeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeIdKeyReleased
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            String id = txtfeId.getText();
            
            String table = "";
            if (rbtndog.isSelected()) {
            table = "Dog";
            } else if (rbtncat.isSelected()) {
            table = "Cat";
            } else if (rbtnrabbit.isSelected()) {
            table = "Rabbit";
            } else if (rbtnbird.isSelected()) {
            table = "Bird";
            }
            
            DefaultTableModel dt = (DefaultTableModel)tableInventory.getModel();
            dt.setRowCount(0);
            
            if (!id.isEmpty()) { // Check if the ID field is not empty
                PreparedStatement pst = con.prepareStatement("SELECT " + table + "_id, Breed, Price, Quantity FROM " + table + " WHERE " + table + "_id = ?");
                pst.setString(1, id);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String breed = rs.getString(2);
                    String price = rs.getString(3);
                    String qty = rs.getString(4);
                    txtfeBreed.setText(breed);
                    txtfePrice.setText(price);
                    txtfeQty.setText(qty);
                } else {
                    txtfeBreed.setText("");
                    txtfePrice.setText("");
                    txtfeQty.setText("");
                }

                do {
                    Object o[] = {rs.getString(table + "_id"), rs.getString("Breed"), rs.getString("Quantity"), rs.getString("Price")};
                    dt.addRow(o);
                } while (rs.next());
            } else {
                txtfeBreed.setText("");
                txtfePrice.setText("");
                txtfeQty.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtfeIdKeyReleased

    private void rbtndogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtndogActionPerformed

    private void txtfeIdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfeIdMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeIdMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JToggleButton btnInv;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnSale;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowtable;
    private javax.swing.JToggleButton btnSrecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imglogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnbird;
    private javax.swing.JRadioButton rbtncat;
    private javax.swing.JRadioButton rbtndog;
    private javax.swing.JRadioButton rbtnrabbit;
    private javax.swing.JTable tableInventory;
    private javax.swing.JLabel txtBreed;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtQty;
    private javax.swing.JLabel txtSearch;
    private javax.swing.JLabel txtcate;
    private javax.swing.JTextField txtfeBreed;
    private javax.swing.JTextField txtfeId;
    private javax.swing.JTextField txtfePrice;
    private javax.swing.JTextField txtfeQty;
    // End of variables declaration//GEN-END:variables
}
