/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshopmanagementsystem;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author heinnaingsoe
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // Center the window on the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setTitle("Login");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpass = new javax.swing.JLabel();
        txtuname = new javax.swing.JLabel();
        txtfeUname = new javax.swing.JTextField();
        txtfepass = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpass.setText("Password");
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtuname.setText("Username");
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        txtfeUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeUnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfeUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, -1));

        txtfepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfepassActionPerformed(evt);
            }
        });
        jPanel1.add(txtfepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, -1));

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopmanagementsystem/Img/paw.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfeUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeUnameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String user = txtfeUname.getText();
            String pwd = txtfepass.getText();
            boolean isAuthenticated = false;
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            Statement st = con.createStatement();
            
            String sql = "SELECT * FROM Login";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String username = rs.getString("username");
                String password = rs.getString("password");
                String role = rs.getString("role");
                
                if(user.equals(username) && pwd.equals(password)){
                    new Inventory(role).setVisible(true);
                    dispose();
                    isAuthenticated = true;
                    break;
                }
            }
            
            if(!isAuthenticated){
                JOptionPane.showMessageDialog(null, "Username or Passwore is incorrect!");
                txtfeUname.setText("");
                txtfepass.setText("");
                txtfeUname.requestFocus();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unknown error occured!");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtfepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtfeUname;
    private javax.swing.JPasswordField txtfepass;
    private javax.swing.JLabel txtpass;
    private javax.swing.JLabel txtuname;
    // End of variables declaration//GEN-END:variables
}
