/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshopmanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heinnaingsoe
 */
public class SaleRecord extends javax.swing.JFrame {

    private String role;
    /**
     * Creates new form SaleRecord
     */
    public SaleRecord(){
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setTitle("Sale Record");
        tableLoad();
    }
    
    public SaleRecord(String role) {
        this.role = role;
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setTitle("Sale Record");
        tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        imglogo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        btnInv = new javax.swing.JToggleButton();
        btnSale = new javax.swing.JToggleButton();
        btnSrecord = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        txtfeTotal = new javax.swing.JTextField();
        txttitle = new javax.swing.JLabel();
        txtcate = new javax.swing.JLabel();
        rbtndog = new javax.swing.JRadioButton();
        rbtnbird = new javax.swing.JRadioButton();
        rbtncat = new javax.swing.JRadioButton();
        rbtnrabbit = new javax.swing.JRadioButton();
        txtId = new javax.swing.JLabel();
        txtfeId = new javax.swing.JTextField();
        rbtnAll = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        saleRecTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopmanagementsystem/Img/animallogo.jpeg"))); // NOI18N
        jPanel2.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 130));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, 30));

        btnInv.setText("Inventory");
        btnInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvActionPerformed(evt);
            }
        });
        jPanel2.add(btnInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 50));

        btnSale.setText("Sale");
        btnSale.setMaximumSize(new java.awt.Dimension(78, 23));
        btnSale.setMinimumSize(new java.awt.Dimension(78, 23));
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        jPanel2.add(btnSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 50));

        btnSrecord.setBackground(new java.awt.Color(153, 255, 255));
        btnSrecord.setText("Sale Record");
        btnSrecord.setMaximumSize(new java.awt.Dimension(78, 23));
        btnSrecord.setMinimumSize(new java.awt.Dimension(78, 23));
        btnSrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrecordActionPerformed(evt);
            }
        });
        jPanel2.add(btnSrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 580));

        jPanel1.setBackground(new java.awt.Color(131, 205, 244));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        txtTotal.setText("Total");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, -1));

        txtfeTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txtfeTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtfeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 170, 50));

        txttitle.setFont(new java.awt.Font("Kefa", 0, 24)); // NOI18N
        txttitle.setText("Pet Shop Sale Record");
        jPanel1.add(txttitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 40));

        txtcate.setText("Category");
        jPanel1.add(txtcate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));

        buttonGroup1.add(rbtndog);
        rbtndog.setText("Dog");
        rbtndog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndogActionPerformed(evt);
            }
        });
        jPanel1.add(rbtndog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 80, -1));

        buttonGroup1.add(rbtnbird);
        rbtnbird.setText("Bird");
        rbtnbird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnbirdActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnbird, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 70, -1));

        buttonGroup1.add(rbtncat);
        rbtncat.setText("Cat");
        rbtncat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtncatActionPerformed(evt);
            }
        });
        jPanel1.add(rbtncat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 70, -1));

        buttonGroup1.add(rbtnrabbit);
        rbtnrabbit.setText("Rabbit");
        rbtnrabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnrabbitActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnrabbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 70, -1));

        txtId.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 14)); // NOI18N
        txtId.setText("Sale_ID");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        txtfeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeIdActionPerformed(evt);
            }
        });
        txtfeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfeIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtfeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, -1));

        buttonGroup1.add(rbtnAll);
        rbtnAll.setText("All");
        rbtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAllActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 660, 160));

        saleRecTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale_ID", "Category", "Breed", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(saleRecTb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Funtion to show data on the sale record table
    private void tableLoad(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            DefaultTableModel dt = (DefaultTableModel)saleRecTb.getModel();
            PreparedStatement pst = con.prepareStatement("SELECT * from SaleRecord");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object o[] = {rs.getString("Sale_id"), rs.getString("Category"), rs.getString("Breed"),rs.getString("Qty"), rs.getString("Price"),rs.getString("Total")};
                dt.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btnTableLoad(String category){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            DefaultTableModel dt = (DefaultTableModel)saleRecTb.getModel();
            dt.setRowCount(0);
            PreparedStatement pst = con.prepareStatement("SELECT * from SaleRecord WHERE Category = ?");
            pst.setString(1, category);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object o[] = {rs.getString("Sale_id"), rs.getString("Category"), rs.getString("Breed"),rs.getString("Qty"), rs.getString("Price"),rs.getString("Total")};
                dt.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvActionPerformed
        // TODO add your handling code here:
        new Inventory(role).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInvActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        // TODO add your handling code here:
        new Sale(role).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSaleActionPerformed

    private void btnSrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSrecordActionPerformed

    private void txtfeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeIdKeyReleased
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/PetShopManagementSysDB","root","");
            DefaultTableModel dt = (DefaultTableModel)saleRecTb.getModel();
            dt.setRowCount(0);
            
            String id = txtfeId.getText();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM SaleRecord WHERE Sale_id = ?");
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();

            while(rs.next()){
                Object o[] = {rs.getString("Sale_id"), rs.getString("Category"), rs.getString("Breed"),rs.getString("Qty"), rs.getString("Price"),rs.getString("Total")};
                dt.addRow(o);
                int total = 0;
                for (int i=0; i<saleRecTb.getRowCount(); i++){
                    total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
                    txtfeTotal.setText(Integer.toString(total));
                }
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtfeIdKeyReleased

    private void txtfeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeIdActionPerformed

    private void rbtnbirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnbirdActionPerformed
        // TODO add your handling code here:
        btnTableLoad(rbtnbird.getText());
        int total = 0;
        for (int i=0; i<saleRecTb.getRowCount(); i++){
            total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
            txtfeTotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_rbtnbirdActionPerformed

    private void rbtncatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtncatActionPerformed
        // TODO add your handling code here:
        btnTableLoad(rbtncat.getText());
        int total = 0;
        for (int i=0; i<saleRecTb.getRowCount(); i++){
            total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
            txtfeTotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_rbtncatActionPerformed

    private void rbtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAllActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel)saleRecTb.getModel();
        dt.setRowCount(0);
        tableLoad();
        int total = 0;
        for (int i=0; i<saleRecTb.getRowCount(); i++){
            total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
            txtfeTotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_rbtnAllActionPerformed

    private void rbtndogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndogActionPerformed
        // TODO add your handling code here:
        btnTableLoad(rbtndog.getText());
        int total = 0;
        for (int i=0; i<saleRecTb.getRowCount(); i++){
            total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
            txtfeTotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_rbtndogActionPerformed

    private void rbtnrabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnrabbitActionPerformed
        // TODO add your handling code here:
        btnTableLoad(rbtnrabbit.getText());
        int total = 0;
        for (int i=0; i<saleRecTb.getRowCount(); i++){
            total += Integer.parseInt(saleRecTb.getValueAt(i, 5).toString());
            txtfeTotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_rbtnrabbitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInv;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnSale;
    private javax.swing.JToggleButton btnSrecord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imglogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAll;
    private javax.swing.JRadioButton rbtnbird;
    private javax.swing.JRadioButton rbtncat;
    private javax.swing.JRadioButton rbtndog;
    private javax.swing.JRadioButton rbtnrabbit;
    private javax.swing.JTable saleRecTb;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtcate;
    private javax.swing.JTextField txtfeId;
    private javax.swing.JTextField txtfeTotal;
    private javax.swing.JLabel txttitle;
    // End of variables declaration//GEN-END:variables
}
